/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yf_jar_jnidemo_JniTest */

#ifndef _Included_com_yf_jar_jnidemo_JniTest
#define _Included_com_yf_jar_jnidemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yf_jar_jnidemo_JniTest
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yf_jar_jnidemo_JniTest_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
